language: node_js
version: 1.0
node_js:
- node
install:
  - npm install
script:
  - npm run lint-ts
  - npm run build
before_deploy:
  - cd dist
deploy:
  edge: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    repo: maximelafarie/browizard
    branch: master
after_deploy:
  - cat /home/travis/.npm/_logs/*-debug.log