language: node_js
node_js:
- 16
install:
  - npm install
script:
  - npm run lint-ts
  - npm run build
before_deploy:
  - cd dist
deploy:
  edge: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    repo: maximelafarie/browizard
    branch: master