language: node_js
version: 1.0
node_js:
- node
- lts/*
install:
  - npm install
script:
  - npm run lint-ts
  - npm run build
deploy:
  local_dir: dist
  edge: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    repo: maximelafarie/browizard
    branch: master
